### PR TITLE
Removed duplicated 'permissions' from models.py. (Fixed #49)

### LINKED ISSUE #49: Permission should not be defined twice.
See https://github.com/OpenSlides/OpenSlides/issues/2901

### PR DESCRIPTION
**Pull request by emanuelschuetze**
@normanjaeckel I removed one of the two 'permissions' and tested it again (see https://github.com/OpenSlides/OpenSlides/issues/2901) - same error:

**django.contrib.auth.models.MultipleObjectsReturned: get() returned more than one Permission -- it returned 2!**

### CODE REVIEW

**Comment by normanjaeckel** [comment]
Did you clean your database? You also have to add a new migrations file (but this has nothing to do with the problem).

**Comment by emanuelschuetze** [comment]
> Did you clean your database?

Yes, I started with an empty personal_data dir. Same error!

**Comment by normanjaeckel** [comment]
Sorry I do not have time to debug this issue. You can try to add a new migrations file and then try again with a clean db. You can also try to debug which permission exists twice by printing out app_label and codename in users/serializers.py before the line where the get call raises the MultipleObjectsReturned error. So you can see which permission exists twice in the database. Then search for the codename string to see where this perm might come in. Also print out settings.INSTALLED_APPS to ensure that the plugin is installed only once.

**Comment by emanuelschuetze** [comment]
Ok, all done. Successfully tested together with @jwinzer . Also renamed the permission string to "can_manage". I'll merge it now...

**Comment by emanuelschuetze** [comment]
Note: Recreate your database is required because migration file is updated.

**Pull request merged**
